#!/usr/bin/env python3
"""Monte Carlo uncertainty propagation for fitted CIA ringdown time.

使用说明
--------
这个脚本用于把原始平均衰荡时间的 A 类标准不确定度传播到最终拟合后的
`tau_fit_us`。核心思想是：

    1. 读取处理后的 `continuum_step2_fit.csv`。
    2. 读取 `scripts/calculate_cia_tau_uncertainty.py` 生成的
       `tau_uncertainty.csv`，获得每个波数点的 `tau_uncertainty_us`。
    3. 每次 Monte Carlo 都生成一组扰动后的衰荡时间：

           tau_i* = tau_i + N(0, u_tau_i)

    4. 对每组扰动数据重新执行相同的拟合流程。
    5. 对每个波数点统计所有拟合结果的标准差，作为拟合后衰荡时间的
       A 类标准不确定度。

默认不覆盖输入 CSV，而是生成新文件：

    <input stem>_mc_uncertainty.csv

常用命令:
    # Ar: 用 continuum Step 2 的 loss 域拟合参数做 Monte Carlo
    python scripts/monte_carlo_tau_fit_uncertainty.py \
      'output/results/continuum/CIA/333K/Ar 500Torr/continuum_step2_fit.csv' \
      --fit-method continuum-step2 \
      --step2-mode ar \
      --cia-fit-window 40 \
      --cia-fit-step 5 \
      --cia-fit-order 2 \
      --cia-fit-sigma 4 \
      --cia-fit-smooth 20 \
      --samples 300

    # O2: 用已有 O2 吸收剔除 mask，重新拟合 CIA 基线
    python scripts/monte_carlo_tau_fit_uncertainty.py \
      'output/results/continuum/CIA/273K/O2 500Torr/continuum_step2_fit.csv' \
      --fit-method continuum-step2 \
      --step2-mode o2 \
      --cia-fit-window 8 \
      --cia-fit-step 1 \
      --cia-fit-order 2 \
      --cia-fit-sigma 2 \
      --cia-fit-smooth 2 \
      --samples 300

    # 如果最终结果还经过 lmfit B-spline 平滑，在 Step 2 后继续执行同样的平滑
    python scripts/monte_carlo_tau_fit_uncertainty.py \
      'output/results/continuum/CIA/273K/Ar 500Torr/continuum_step2_fit.csv' \
      --fit-method continuum-step2 \
      --step2-mode ar \
      --cia-fit-window 40 \
      --cia-fit-step 5 \
      --cia-fit-order 2 \
      --cia-fit-sigma 4 \
      --cia-fit-smooth 20 \
      --post-lmfit-spline \
      --knots-every 15 \
      --smooth-lambda 0.1 \
      --samples 300

    # 只对某一列直接做 lmfit B-spline Monte Carlo
    python scripts/monte_carlo_tau_fit_uncertainty.py \
      'output/results/continuum/CIA/273K/Ar 500Torr/continuum_step2_fit.csv' \
      --fit-method lmfit-spline \
      --fit-column tau_us \
      --knots-every 15 \
      --smooth-lambda 0.1 \
      --samples 300

输出新增列:
    tau_mc_input_uncertainty_us
        输入平均衰荡时间的 A 类标准不确定度。
    tau_fit_us_mc_mean
        Monte Carlo 拟合结果的平均值。
    tau_fit_us_mc_uncertainty_us
        Monte Carlo 拟合结果的标准差，即拟合后衰荡时间的 A 类标准不确定度。
    tau_fit_us_mc_ci_low_us / tau_fit_us_mc_ci_high_us
        默认 95% Monte Carlo 分位区间。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import apply_lmfit_spline_region as lmfit_spline  # noqa: E402

from crds_process.continuum.analysis import (  # noqa: E402
    TAU_US_TO_PPM_PER_CM,
    _add_o2_hitran_subtraction,
    _fit_loss_values,
    _hitran_absorption_mask,
    _normalize_fit_mode,
    _resolve_fit_mode,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Propagate tau uncertainty to fitted tau by Monte Carlo.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("csv_path", type=Path, help="Processed continuum CSV.")
    parser.add_argument(
        "--uncertainty-csv",
        type=Path,
        help=(
            "tau_uncertainty.csv generated by calculate_cia_tau_uncertainty.py. "
            "Default: infer from the continuum/CIA path."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output CSV. Default: <input stem>_mc_uncertainty.csv.",
    )
    parser.add_argument("--x-column", default="wavenumber", help="Wavenumber column.")
    parser.add_argument(
        "--tau-column",
        default="tau_us",
        help="Measured tau column to perturb for continuum-step2.",
    )
    parser.add_argument(
        "--uncertainty-column",
        default="tau_uncertainty_us",
        help="Tau uncertainty column in --uncertainty-csv.",
    )
    parser.add_argument(
        "--uncertainty-x-column",
        default="wavenumber",
        help="Wavenumber column in --uncertainty-csv.",
    )
    parser.add_argument(
        "--merge-tolerance",
        type=float,
        default=0.005,
        help="Maximum wavenumber mismatch when merging uncertainty, in cm-1.",
    )
    parser.add_argument("--samples", type=int, default=300, help="Monte Carlo samples.")
    parser.add_argument("--seed", type=int, default=20260512, help="Random seed.")
    parser.add_argument(
        "--confidence",
        type=float,
        default=0.95,
        help="Central confidence interval written from MC quantiles.",
    )
    parser.add_argument(
        "--min-tau-us",
        type=float,
        default=1e-9,
        help="Lower bound after random perturbation, to keep tau positive.",
    )
    parser.add_argument(
        "--fit-method",
        choices=("continuum-step2", "lmfit-spline"),
        default="continuum-step2",
        help="Fitting process repeated for every Monte Carlo sample.",
    )
    parser.add_argument(
        "--output-prefix",
        default="tau_fit_us_mc",
        help="Prefix of generated MC output columns.",
    )
    parser.add_argument(
        "--plot",
        type=Path,
        help="Optional PNG showing final fit and MC uncertainty band.",
    )

    # Continuum Step 2 parameters.
    parser.add_argument(
        "--step2-mode",
        "--continuum-step2-mode",
        choices=("auto", "ar", "o2"),
        default="auto",
        help="Continuum Step 2 mode used in Monte Carlo.",
    )
    parser.add_argument(
        "--pressure-label",
        help="Pressure label, e.g. 'Ar 500Torr' or 'O2 500Torr'. Default: infer from path.",
    )
    parser.add_argument("--cia-fit-window", type=float, default=20.0, help="Step 2 fit window in cm-1.")
    parser.add_argument("--cia-fit-step", type=float, default=5.0, help="Step 2 fit step in cm-1.")
    parser.add_argument("--cia-fit-order", type=int, default=2, help="Step 2 polynomial order.")
    parser.add_argument("--cia-fit-sigma", type=float, default=4.0, help="Step 2 robust sigma.")
    parser.add_argument("--cia-fit-smooth", type=float, default=0.0, help="Step 2 smoothing width in cm-1.")

    # lmfit B-spline parameters, either direct or post-step2.
    parser.add_argument(
        "--fit-column",
        default="tau_us",
        help="Column fitted directly when --fit-method lmfit-spline.",
    )
    parser.add_argument(
        "--post-lmfit-spline",
        action="store_true",
        help="After continuum-step2, apply lmfit B-spline to tau_fit_us for every sample.",
    )
    parser.add_argument("--knots-every", type=float, default=40.0, help="lmfit B-spline knot spacing.")
    parser.add_argument("--n-knots", type=int, help="lmfit B-spline internal knot count.")
    parser.add_argument(
        "--region",
        action="append",
        nargs=3,
        metavar=("START", "END", "KNOTS_EVERY"),
        type=float,
        help="Regional lmfit B-spline setting. Can be repeated.",
    )
    parser.add_argument("--anchor-width", type=float, default=5.0, help="Regional fit anchor width.")
    parser.add_argument("--smooth-lambda", type=float, default=0.0, help="B-spline smooth penalty.")
    parser.add_argument(
        "--fit-range",
        nargs=2,
        metavar=("START", "END"),
        type=float,
        help="Fit range for global lmfit B-spline.",
    )
    parser.add_argument(
        "--weights-column",
        help="Optional uncertainty column used as lmfit-spline weights.",
    )
    return parser.parse_args()


def infer_uncertainty_csv(csv_path: Path) -> Path:
    parts = csv_path.resolve().parts
    try:
        continuum_idx = parts.index("continuum")
        cia_idx = continuum_idx + 1
        if parts[cia_idx] != "CIA":
            raise ValueError
    except (ValueError, IndexError):
        raise SystemExit(
            "Cannot infer --uncertainty-csv from path. Please pass it explicitly."
        ) from None

    group_parts = parts[cia_idx + 1 : -1]
    if len(group_parts) < 2:
        raise SystemExit(
            "Cannot infer --uncertainty-csv because the continuum path is not "
            "continuum/CIA/{temperature}/{gas pressure}/..."
        )
    return PROJECT_ROOT / "output" / "results" / "uncertainty" / "CIA" / Path(*group_parts) / "tau_uncertainty.csv"


def infer_pressure_label(csv_path: Path) -> str:
    parent = csv_path.resolve().parent
    return parent.name


def default_output_path(csv_path: Path) -> Path:
    return csv_path.with_name(f"{csv_path.stem}_mc_uncertainty.csv")


def normalize_range(values: list[float] | tuple[float, float] | None) -> tuple[float, float] | None:
    if values is None:
        return None
    start, end = float(values[0]), float(values[1])
    return (start, end) if start <= end else (end, start)


def read_base_table(args: argparse.Namespace) -> pd.DataFrame:
    csv_path = args.csv_path.expanduser().resolve()
    if not csv_path.is_file():
        raise SystemExit(f"Input CSV does not exist: {csv_path}")
    df = pd.read_csv(csv_path)
    required = [args.x_column]
    if args.fit_method == "continuum-step2":
        required.append(args.tau_column)
    else:
        required.append(args.fit_column)
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise SystemExit(f"{csv_path} is missing columns: {', '.join(missing)}")
    return df


def read_uncertainty_table(args: argparse.Namespace) -> pd.DataFrame:
    uncertainty_csv = (
        args.uncertainty_csv.expanduser().resolve()
        if args.uncertainty_csv
        else infer_uncertainty_csv(args.csv_path)
    )
    if not uncertainty_csv.is_file():
        raise SystemExit(f"Uncertainty CSV does not exist: {uncertainty_csv}")
    df = pd.read_csv(uncertainty_csv)
    missing = [
        col
        for col in (args.uncertainty_x_column, args.uncertainty_column)
        if col not in df.columns
    ]
    if missing:
        raise SystemExit(f"{uncertainty_csv} is missing columns: {', '.join(missing)}")
    return df


def attach_tau_uncertainty(
    base_df: pd.DataFrame,
    uncertainty_df: pd.DataFrame,
    args: argparse.Namespace,
) -> pd.DataFrame:
    base = base_df.copy()
    base["_mc_original_order"] = np.arange(len(base), dtype=int)
    left = base.sort_values(args.x_column)
    right = (
        uncertainty_df[[args.uncertainty_x_column, args.uncertainty_column]]
        .dropna()
        .sort_values(args.uncertainty_x_column)
        .rename(columns={
            args.uncertainty_x_column: "_mc_unc_wavenumber",
            args.uncertainty_column: "tau_mc_input_uncertainty_us",
        })
    )
    merged = pd.merge_asof(
        left,
        right,
        left_on=args.x_column,
        right_on="_mc_unc_wavenumber",
        direction="nearest",
        tolerance=float(args.merge_tolerance),
    )
    merged = merged.sort_values("_mc_original_order").drop(columns=["_mc_original_order"])
    if "_mc_unc_wavenumber" in merged.columns:
        merged = merged.drop(columns=["_mc_unc_wavenumber"])

    sigma = pd.to_numeric(merged["tau_mc_input_uncertainty_us"], errors="coerce")
    missing = int((~np.isfinite(sigma) | (sigma <= 0)).sum())
    if missing:
        raise SystemExit(
            f"{missing} rows did not receive a positive finite tau uncertainty. "
            "Increase --merge-tolerance or check the wavenumber grids."
        )
    return merged


def with_sampled_tau(
    base_df: pd.DataFrame,
    tau_column: str,
    sampled_tau: np.ndarray,
) -> pd.DataFrame:
    work = base_df.copy()
    work[tau_column] = sampled_tau
    if tau_column != "tau_us":
        work["tau_us"] = sampled_tau
    tau = pd.to_numeric(work["tau_us"], errors="coerce").to_numpy(dtype=float)
    work["loss_ppm_per_cm"] = TAU_US_TO_PPM_PER_CM / tau
    return work


def o2_fit_mask_from_table(work: pd.DataFrame, pressure_label: str) -> np.ndarray:
    if "o2_fit_used" in work.columns:
        return work["o2_fit_used"].astype(bool).to_numpy()

    hitran_work = _add_o2_hitran_subtraction(work, pressure_label=pressure_label)
    absorption_mask, _ = _hitran_absorption_mask(
        wavenumber=hitran_work["wavenumber"].to_numpy(dtype=float),
        hitran_loss=hitran_work["hitran_o2_loss_ppm_per_cm"].to_numpy(dtype=float),
    )
    finite = (
        np.isfinite(hitran_work["wavenumber"].to_numpy(dtype=float))
        & np.isfinite(hitran_work["loss_ppm_per_cm"].to_numpy(dtype=float))
    )
    return finite & ~absorption_mask


def continuum_step2_fit(
    work: pd.DataFrame,
    args: argparse.Namespace,
    active_mode: str,
    o2_fit_mask: np.ndarray | None,
) -> np.ndarray:
    wn = pd.to_numeric(work[args.x_column], errors="coerce").to_numpy(dtype=float)
    loss = pd.to_numeric(work["loss_ppm_per_cm"], errors="coerce").to_numpy(dtype=float)
    fit_mask = o2_fit_mask if active_mode == "o2" else None
    fitted_loss = _fit_loss_values(
        wn=wn,
        loss=loss,
        fit_mask=fit_mask,
        window_cm1=args.cia_fit_window,
        step_cm1=args.cia_fit_step,
        order=args.cia_fit_order,
        sigma=args.cia_fit_sigma,
        smooth_cm1=args.cia_fit_smooth,
        error_label=f"Monte Carlo {active_mode} Step 2 fit",
    )
    return TAU_US_TO_PPM_PER_CM / fitted_loss


def lmfit_spline_fit(
    work: pd.DataFrame,
    args: argparse.Namespace,
    y_column: str,
) -> np.ndarray:
    lmfit_spline.load_dependencies()
    output_column = "_mc_lmfit_spline_output"
    fit_range = normalize_range(args.fit_range)
    if args.region:
        if args.n_knots is not None:
            raise SystemExit("--region cannot be combined with --n-knots")
        lmfit_spline.fit_regional_splines(
            df=work,
            x_column=args.x_column,
            y_column=y_column,
            output_column=output_column,
            regions=args.region,
            anchor_width=args.anchor_width,
            smooth_lambda=args.smooth_lambda,
            weights_column=args.weights_column,
        )
    else:
        lmfit_spline.fit_global_spline(
            df=work,
            x_column=args.x_column,
            y_column=y_column,
            output_column=output_column,
            knots_every=args.knots_every,
            n_knots=args.n_knots,
            smooth_lambda=args.smooth_lambda,
            fit_range=fit_range,
            weights_column=args.weights_column,
        )
    return pd.to_numeric(work[output_column], errors="coerce").to_numpy(dtype=float)


def run_single_fit(
    base_df: pd.DataFrame,
    sampled_tau: np.ndarray,
    args: argparse.Namespace,
    active_mode: str,
    o2_fit_mask: np.ndarray | None,
) -> np.ndarray:
    if args.fit_method == "lmfit-spline":
        work = base_df.copy()
        work[args.fit_column] = sampled_tau
        return lmfit_spline_fit(work, args, y_column=args.fit_column)

    work = with_sampled_tau(base_df, args.tau_column, sampled_tau)
    fitted_tau = continuum_step2_fit(work, args, active_mode=active_mode, o2_fit_mask=o2_fit_mask)
    if not args.post_lmfit_spline:
        return fitted_tau

    work["tau_fit_us"] = fitted_tau
    return lmfit_spline_fit(work, args, y_column="tau_fit_us")


def monte_carlo_fit(base_df: pd.DataFrame, args: argparse.Namespace) -> tuple[np.ndarray, str]:
    if args.samples < 2:
        raise SystemExit("--samples must be at least 2")
    if not 0 < args.confidence < 1:
        raise SystemExit("--confidence must be between 0 and 1")

    pressure_label = args.pressure_label or infer_pressure_label(args.csv_path)
    active_mode = "lmfit-spline"
    o2_fit_mask = None
    if args.fit_method == "continuum-step2":
        active_mode = _resolve_fit_mode(_normalize_fit_mode(args.step2_mode), pressure_label)
        if active_mode == "o2-hitran":
            raise SystemExit("o2-hitran does not produce a fitted tau baseline; use --step2-mode o2.")
        if active_mode == "o2":
            base_work = with_sampled_tau(
                base_df,
                args.tau_column,
                pd.to_numeric(base_df[args.tau_column], errors="coerce").to_numpy(dtype=float),
            )
            o2_fit_mask = o2_fit_mask_from_table(base_work, pressure_label=pressure_label)

    rng = np.random.default_rng(args.seed)
    if args.fit_method == "lmfit-spline":
        y0 = pd.to_numeric(base_df[args.fit_column], errors="coerce").to_numpy(dtype=float)
    else:
        y0 = pd.to_numeric(base_df[args.tau_column], errors="coerce").to_numpy(dtype=float)
    sigma = pd.to_numeric(base_df["tau_mc_input_uncertainty_us"], errors="coerce").to_numpy(dtype=float)
    if not np.all(np.isfinite(y0) & (y0 > 0)):
        raise SystemExit("Input tau/fit column contains non-positive or non-finite values.")

    results = np.empty((args.samples, len(base_df)), dtype=float)
    report_every = max(1, args.samples // 10)
    for idx in range(args.samples):
        sampled = y0 + rng.normal(loc=0.0, scale=sigma, size=len(y0))
        sampled = np.maximum(sampled, args.min_tau_us)
        results[idx] = run_single_fit(
            base_df=base_df,
            sampled_tau=sampled,
            args=args,
            active_mode=active_mode,
            o2_fit_mask=o2_fit_mask,
        )
        if (idx + 1) % report_every == 0 or idx + 1 == args.samples:
            print(f"  MC sample {idx + 1}/{args.samples}")
    return results, active_mode


def add_mc_columns(base_df: pd.DataFrame, samples: np.ndarray, args: argparse.Namespace) -> pd.DataFrame:
    out = base_df.copy()
    prefix = args.output_prefix
    alpha = (1.0 - args.confidence) / 2.0
    low_q = 100.0 * alpha
    high_q = 100.0 * (1.0 - alpha)

    mean = np.nanmean(samples, axis=0)
    std = np.nanstd(samples, axis=0, ddof=1)
    out[f"{prefix}_mean_us"] = mean
    out[f"{prefix}_uncertainty_us"] = std
    out[f"{prefix}_rel_uncertainty"] = std / np.abs(mean)
    out[f"{prefix}_ci_low_us"] = np.nanpercentile(samples, low_q, axis=0)
    out[f"{prefix}_ci_high_us"] = np.nanpercentile(samples, high_q, axis=0)
    out[f"{prefix}_samples"] = int(args.samples)
    out[f"{prefix}_seed"] = int(args.seed)
    return out


def save_plot(out: pd.DataFrame, args: argparse.Namespace) -> None:
    if not args.plot:
        return
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    prefix = args.output_prefix
    x = pd.to_numeric(out[args.x_column], errors="coerce").to_numpy(dtype=float)
    mean = pd.to_numeric(out[f"{prefix}_mean_us"], errors="coerce").to_numpy(dtype=float)
    unc = pd.to_numeric(out[f"{prefix}_uncertainty_us"], errors="coerce").to_numpy(dtype=float)
    mask = np.isfinite(x) & np.isfinite(mean) & np.isfinite(unc)

    fig, ax = plt.subplots(figsize=(11, 5), dpi=200)
    ax.plot(x[mask], mean[mask], lw=1.3, color="tab:red", label=f"{prefix}_mean_us")
    ax.fill_between(
        x[mask],
        mean[mask] - unc[mask],
        mean[mask] + unc[mask],
        color="tab:red",
        alpha=0.22,
        linewidth=0,
        label="1 sigma",
    )
    ax.set_xlabel("Wavenumber (cm-1)")
    ax.set_ylabel("tau_fit_us")
    ax.grid(alpha=0.25)
    ax.legend()
    fig.tight_layout()
    plot_path = args.plot.expanduser().resolve()
    plot_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(plot_path)
    plt.close(fig)
    print(f"Plot: {plot_path}")


def main() -> None:
    args = parse_args()
    args.csv_path = args.csv_path.expanduser().resolve()
    output_path = (
        args.output.expanduser().resolve()
        if args.output
        else default_output_path(args.csv_path).resolve()
    )

    base_df = read_base_table(args)
    uncertainty_df = read_uncertainty_table(args)
    base_df = attach_tau_uncertainty(base_df, uncertainty_df, args)

    print(f"Input CSV: {args.csv_path}")
    print(f"Output CSV: {output_path}")
    print(f"Fit method: {args.fit_method}")
    print(f"Samples: {args.samples}")

    samples, active_mode = monte_carlo_fit(base_df, args)
    out = add_mc_columns(base_df, samples, args)
    out[f"{args.output_prefix}_fit_method"] = args.fit_method
    out[f"{args.output_prefix}_active_mode"] = active_mode

    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)
    save_plot(out, args)

    uncertainty_col = f"{args.output_prefix}_uncertainty_us"
    uncertainty = pd.to_numeric(out[uncertainty_col], errors="coerce")
    print(f"Updated rows: {len(out)}")
    print(f"Mean fitted tau uncertainty: {float(uncertainty.mean()):.8g} us")
    print(f"Median fitted tau uncertainty: {float(uncertainty.median()):.8g} us")
    print(f"Max fitted tau uncertainty: {float(uncertainty.max()):.8g} us")
    print(f"Wrote: {output_path}")


if __name__ == "__main__":
    main()
